### ISSUE TITLE
RNG dependency 

### ISSUE THREAD

**Issue by cjpatton** [rozbb/rust-hpke#14]
I recently tried to compile this crate to WASM for use in a JavaScript application. I ran into some dependency issues and was wondering if you'd be amendable to changing the dependencies.

I'm fairly new to WASM, but as far as I can tell, there's no way to do this with the current set of dependencies. Specifically, the version of the `rand` crate that's needed no longer supports WASM. You used to be able to do something like this (in Cargo.toml):
```
rand = { version = "0.7", features = ["wasm-bindgen"] }
```
but in version 0.8, the "wasm-bindgen" feature is no longer supported. Downgrading to 0.7 is also not possible without breaking the API, since this crate uses traits that are defined in 0.8 but not 0.7.

After studying the code, It seems like you can get away with using the much lighter weight [`getrandom` crate](https://crates.io/crates/getrandom):
```
getrandom = { version = "0.2.3", features = [ "js" ] }
```
This just provides a simple wrapper around whatever the system's RNG is (e.g., `/dev/urandom` on Linux). It seems to me that this would suffice, since you're not using the fancier features of `rand`.

I have a PR ready to review, if you're interested in going in this direction. It breaks the API, but in a way that simplifies it quite a bit (no need for an Rng trait everywhere).

**Comment by rozbb** [comment]
I'm a bit hesitant to do this, since it would mean that `HpkeError` now has to have `RngError` variant, or the affected methods would have to panic on randomness depletion. It seems cleaner to me to take in an `R: RngCore` and let the user figure out how to make `R`. You're right that `rand` is too large a dependency, so I restricted it to `rand_core`.

I looked at the `rand` README and it seems like [WASM support](https://github.com/rust-random/rand/tree/453431146dfe3cd3d93005c5cd65dffd72f7e7ae#wasm-support) is available using a method different than you described above. Specifically, you just use the dependencies
```
hpke = "0.6"
rand_core = { version = "0.6", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }
```
Does that method not work?

**Comment by cjpatton** [comment]
> I'm a bit hesitant to do this, since it would mean that `HpkeError` now has to have `RngError` variant, or the affected methods would have to panic on randomness depletion. It seems cleaner to me to take in an `R: RngCore` and let the user figure out how to make `R`. You're right that `rand` is too large a dependency, so I restricted it to `rand_core`.

We recently made a similar change [here](https://github.com/abetterinternet/libprio-rs/) (see [this PR](https://github.com/abetterinternet/libprio-rs/pull/55)) and concluded that it's best to propagate the error where it occurs. See [this code](https://github.com/abetterinternet/libprio-rs/blob/3a3557ac9a9e787eb54aa4e613bc9bfa62fabd1c/src/encrypt.rs#L37-L39) for example. This seems preferable to panicking, which, AFAICT, is what `rand` must do if it's backed by `getrandom`.
 
> I looked at the `rand` README and it seems like [WASM support](https://github.com/rust-random/rand/tree/453431146dfe3cd3d93005c5cd65dffd72f7e7ae#wasm-support) is available using a method different than you described above. Specifically, you just use the dependencies
> 
> ```
> hpke = "0.6"
> rand_core = { version = "0.6", features = ["getrandom"] }
> getrandom = { version = "0.2", features = ["js"] }
> ```
> 
> Does that method not work?

TBH I totally missed this solution. I'll double check that it works, but you may consider this issue closed.

That said, getting rid of the dependency altogether would be a better solution for my use case, given that the code size is an important consideration for WASM.

**Comment by rozbb** [comment]
It seems like there's still good reason to take an RNG though. If the amount of entropy on a system is limited (for whatever weird reason), then a caller can only afford a certain number of calls to `getrandom()`. In that setting, it makes most sense to seed an RNG with system entropy and then use the RNG for the rest of the session.

If a user wants to fallibly instantiate an RNG, they can always do
```rust
let mut seed = ChaCha8Core::Seed::default();
if getrandom::getrandom(seed.as_mut()).is_ok() {
    let csprng = ChaCha8Core::from_seed(seed);
    // ...
}
else {
    // whatever
}
```

Finally, regarding code size, I'm only seeing a ~1.4% decrease in binary size on my machine with your changes. Albeit, I'm not compiling to WASM, but maybe it's a good proxy.

**Comment by cjpatton** [comment]
That's a fair point :)

> Finally, regarding code size, I'm only seeing a ~1.4% decrease in binary size on my machine with your changes. Albeit, I'm not compiling to WASM, but maybe it's a good proxy.

Unfortunately I'm not set up to make a 1:1 comparison for my application. I remember it being significant enough to be worth mentioning, but it's not really a deal breaker. My main concern is getting it to compile, and there seems to be a path to doing so.
