### ISSUE TITLE
kem::encap_with_eph parameters disambiguition

### ISSUE THREAD

**Issue by BoOTheFurious** [rozbb/rust-hpke#24]
Hello,

What is the purpose of the `sk_eph: Self::PrivateKey` parameter in the `kem::encap_with_eph` function.
The name suggest it is the ephemeral secret but it's the role of this function to generate it and it is not coherent with the type.
This parameters seems to be useless. Is there something I did not understand ?

Regards

**Comment by rozbb** [comment]
`encap_with_eph` doesn't generate its own ephemeral secret, in fact, it doesn't even  take an RNG as input. Generating `sk_eph` is the job of `encap`. I split out the functionality because 1) it's slightly easier this way and 2) I need `encap_with_eph` for running test vectors.

**Comment by rozbb** [comment]
Fixed in #27
