### ISSUE TITLE
kem::derive_keypair and label expansion

### ISSUE THREAD

**Issue by BoOTheFurious** [rozbb/rust-hpke#25]
Hello,

When implementing the `kem` trait for my own algorithm, I need to implement the `derive_keypair` function. If I want to follow the RFC I need to use the same label and `VERSION_LABEL` for the kdf expansion. But these variables are private. Is it possible to make them public or have some public functions to ease the expansion (such as the `extract_and_expand` and `label_extract` function which are not public) ?

Regards,

**Comment by rozbb** [comment]
Good idea, I'll export `extract_and_expand` and `label_extract`, but keep them `#[doc(hidden)]`. Does that work for you?

**Comment by BoOTheFurious** [comment]
It seems good for me, thanks

**Comment by rozbb** [comment]
Fixed in #27
