### ISSUE TITLE
Constrain Kem::PublicKey to Implement Debug

### ISSUE THREAD

**Issue by ycscaly** [rozbb/rust-hpke#34]
The PublicKey type of Kem does not constrain to Debug:
https://github.com/rozbb/rust-hpke/blob/master/src/kem.rs#L20-L24

The inner key does, however:
https://github.com/rozbb/rust-hpke/blob/master/src/dhkex/x25519.rs#L182-L186

I am writing a program that relies on this crate, and in order for a struct that I write that holds a PublicKey to implement Debug, so must the PublicKey. I could skip printing public keys, but I argue that this could in fact provide helpful information in some cases.

**Comment by ycscaly** [comment]
PartialEq is also needed.

**Comment by rozbb** [comment]
Resolved in #42
