### ISSUE TITLE
Work with RustCrypto's traits for Kem, KDF, and AEAD

### ISSUE THREAD

**Issue by ycscaly** [rozbb/rust-hpke#37]
Currently, this library works with wrapper traits for Kem, Kdf, and Aead. Internally, it uses RustCrypto's Kdf & Aead. 
I suggest that it should use RustCrypto's traits directly.
From the user perspective, it makes much more sense and will remove duplicative requirements and generic parameters.

**Comment by ycscaly** [comment]
There are a lot of benefits for this.

From a structure that depends on (RustCrypto's) `<C: PrimeCurve + CurveArithmetics, A: Aead, H: Digest>` we can and should be able to derive a corresponding `Kdf<H>` and `Kem<C>`, and thus be able to call the `single_shot()` API.

**Comment by rozbb** [comment]
I like this idea, but I have two major problems with it:

1. HPKE is not really intended to be KEM-independent. It's specced out for specific DHKEMs, and [includes](https://cfrg.github.io/draft-irtf-cfrg-hpke/draft-irtf-cfrg-hpke.html#section-7.1.4) KEM-specific validation steps.
2. The `kem` traits are too general to be used in this context. For example, `kem` traits say nothing about how to derive an `AuthEncapsulator` context. We know in the case of HPKE that it's sufficient to do ordinary keygen and use a DH static secret key in the encapsulation process. But that's specialized to DHKEMs.

**Comment by rozbb** [comment]
Even if talking about DHKEMs, it's not something that's currently possible. x25519 and P-256 ECDH have their own APIs for computing Diffie Hellman secrets. They happen to be doing the same thing, but that doesn't make it a good idea to implement it here from scratch. There's other idiosyncracies, like the fact that x25519 private keys need to be clamped scalars. I don't think it would be safe to extend HPKE to generic curves.

**Comment by rozbb** [comment]
As a more general point, this crate is supposed to be as conservative as possible in terms of security. The `Kdf`, `Aead`, and `Kem` traits are all public, and you can impl them for external types if you really want. For the first two, it isn't even hard. But this process should not be made too easy. There is value in adhering to a standard, and I haven't seen any proposals (even informal ones) to extend HPKE to a new KDF, AEAD, or curve.

Closing for now.

**Comment by ycscaly** [comment]
Thanks for the explanation.

By no proposals, you mean schemes, not code right? as if, the specific choice of KDF, aead, and kem that you bundled together were actually written explicitly as known-good parameters?

**Comment by rozbb** [comment]
Yeah exactly

**Comment by ycscaly** [comment]
Thanks, I understand and agree with your reasoning now.
