### ISSUE TITLE
compatibility with serde

### ISSUE THREAD

**Issue by uzukio** [rozbb/rust-hpke#5]
Hi, the (de)serialization options manually call `to/from_bytes`, but it'd be great if we had implementations for the Serialize/Deserialize traits in serde, perhaps behind a feature.

**Comment by rozbb** [comment]
This is a great idea. Shouldn't be too much work. I'll add to my list of TODOs

**Comment by migueldemoura** [comment]
Hi there, I think this is nice to have as well.
In my case, I've only felt the need to implement said traits for `EncappedKey<T>` and `AeadTag<T>` since those are the only ones that I end up (de)serializing. That may not be as clean as what you're trying to do.

**Comment by rozbb** [comment]
Implemented everything in version 0.2.1 🙌
