### ISSUE TITLE
How to only use a public key?

### ISSUE THREAD

**Issue by kamiyaa** [rozbb/rust-hpke#60]
Is there a way to parse an existing `Kem::PublicKey` without the private key?
i.e. from a string?

**Comment by rozbb** [comment]
Yes you can. [`Kem::PublicKey` implements  Deserializable](https://docs.rs/hpke/latest/hpke/trait.Kem.html#associatedtype.PublicKey). So you can use that parse a public key via the from_bytes method On Jun 6, 2024, at 21:43, Jeff Zhao ***@***.***> wrote:﻿
Is there a way to parse an existing Kem::PublicKey without the private key?
i.e. from a string?

**Comment by kamiyaa** [comment]
Right, but is Kem::PublicKey a private struct or something?
I can't seem to access it in any way.

**Comment by rozbb** [comment]
What have you tried? I have the following working:
```rust
use hpke::{Kem as KemTrait, Deserializable, kem::X25519HkdfSha256};
type MyKem = X25519HkdfSha256;
type Pubkey = <MyKem as KemTrait>::PublicKey;
// ... later on 
let reconstructed_pubkey = Pubkey.from_bytes(&bytes).expect("deser failed");
```

**Comment by kamiyaa** [comment]
> What have you tried? I have the following working:
> 
> ```rust
> use hpke::{Kem as KemTrait, Deserializable, kem::X25519HkdfSha256};
> type MyKem = X25519HkdfSha256;
> type Pubkey = <MyKem as KemTrait>::PublicKey;
> // ... later on 
> let reconstructed_pubkey = Pubkey.from_bytes(&bytes).expect("deser failed");
> ```

Ah thank you! I was struggling with all the different traits and casting required to get it working
