### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by istankovic** [rozbb/rust-hpke#62]
In [Wire](https://github.com/wireapp), we'd like to get rid of our fork of `rust-hpke` and go back to tracking the upstream closely. It would be nice if 0.12 were released so we can make use of P-521.

**Comment by rozbb** [comment]
Hi Ivan. Just released 0.12. Changelog [here](https://github.com/rozbb/rust-hpke/blob/main/CHANGELOG.md#0120---2024-07-03). Thanks for the nudge!

**Comment by istankovic** [comment]
Thank you so much, that was real quick! :purple_heart:
