### ISSUE TITLE
p256 kex result Y-parity bit?

### ISSUE THREAD

**Issue by tomtau** [rozbb/rust-hpke#7]
https://github.com/rozbb/rust-hpke/blob/master/src/kex/ecdh_nistp.rs#L124

for the compressed representation, it's "0x02 | | x-coord" or "0x03 || x-coord" depending on the least significant bit of y-coord.

probably the comment could be corrected + explain why it's discarded (my guess is that it doesn't matter here or it could perhaps be optionally exposed for some advanced/more fancy constructions over hpke?)

**Comment by rozbb** [comment]
Good catch! I think https://github.com/rozbb/rust-hpke/commit/1cbc3eb5146eb10807de1f5929dfb169fc424ac6 addresses this. Can you take a look and close the issue if it's all good?

**Comment by tomtau** [comment]
lgtm
